### ISSUE TITLE
[Feat] 동네소식 API 구현 - WEB

### ISSUE THREAD

**Issue by proysm** [UMC-5th-Coumo/Coumo_Server#9]
# 🛠️ ISSUE
- WEB(사장님) 동네소식 API

# 📑 To-Do
- [ ] 글쓰기
- [ ] 내가 쓴 글 보기
- [ ] 내가 쓴 글 세부내용 보기 = 내가 쓴 글 수정하기
- [ ] 수정 완료 버튼
- [ ] 내가 쓴 글 삭제하기

**Comment by khwoowoo** [comment]
브랜치 생성을 main으로 해서 아직 도메인, 응답 API 코드 등등 없는 파일인 것 같습니다!

**Comment by proysm** [comment]
> 브랜치 생성을 main으로 해서 아직 도메인, 응답 API 코드 등등 없는 파일인 것 같습니다!

제가 잘 이해를 못했습니다..! 
지금 develop 브랜치에서 feat/#9 생성해서 개발하고 있습니다.
혹시 어떤 부분을 말하는건가요?

**Comment by khwoowoo** [comment]
아 깃허브에서 보면 main에서 가져온 것 같아서요! 혹시 저번에 올린 파일이 있나요?? 
<img width="1317" alt="스크린샷 2024-01-22 오후 10 41 57" src="https://github.com/UMC-5th-Coumo/Coumo_Server/assets/23547185/4aee3fd8-1f9a-4678-bbaf-be1ee78baa66">

만약에 없다면 develop에서 풀하시고 다음에는 이렇게해주시면 될 것 같습니다!
<img width="442" alt="스크린샷 2024-01-22 오후 10 38 29" src="https://github.com/UMC-5th-Coumo/Coumo_Server/assets/23547185/01ad3866-6232-4b36-b1e0-565185cfce9d">
<img width="501" alt="스크린샷 2024-01-22 오후 10 38 07" src="https://github.com/UMC-5th-Coumo/Coumo_Server/assets/23547185/f102a682-eff1-4702-a494-e7a8d22bd539">

**Comment by proysm** [comment]
악.

닫고 다시 할게요 ㅎㅎ 그게 맘 편할거 같슴당
